# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.box = "ubuntu/vivid64"
    config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"

    config.vm.define :ubuntu2511_01 do |ubuntu|
        #ubuntu.vm.network :public_network, :bridge => "en0: Wi-Fi (AirPort)" # DHCP
        ubuntu.vm.network :public_network, :bridge => "en0: Wi-Fi (AirPort)", ip: "192.168.1.220" # FIXED IP

        ubuntu.vm.provider 'virtualbox' do |vb|
            vb.customize ['modifyvm', :id, '--name', ubuntu]
            vb.customize ['modifyvm', :id, '--cpus', '1']
            vb.customize ['modifyvm', :id, '--memory', 1024]
            vb.customize ['modifyvm', :id, '--ioapic', 'off']
            vb.customize ['modifyvm', :id, '--nictype1', 'virtio']
            vb.customize ['modifyvm', :id, '--nictype2', 'virtio']
        end
    end

    config.vm.define :ubuntu2511_02 do |ubuntu|
        #ubuntu.vm.network :public_network, :bridge => "en0: Wi-Fi (AirPort)" # DHCP
        ubuntu.vm.network :public_network, :bridge => "en0: Wi-Fi (AirPort)", ip: "192.168.1.221" # FIXED IP

        ubuntu.vm.provider 'virtualbox' do |vb|
            vb.customize ['modifyvm', :id, '--name', ubuntu]
            vb.customize ['modifyvm', :id, '--cpus', '1']
            vb.customize ['modifyvm', :id, '--memory', 1024]
            vb.customize ['modifyvm', :id, '--ioapic', 'off']
            vb.customize ['modifyvm', :id, '--nictype1', 'virtio']
            vb.customize ['modifyvm', :id, '--nictype2', 'virtio']
        end
    end

    # Ansible provisioning
    config.vm.provision "ansible" do |ansible|
        ansible.playbook = "info.yml"

        ansible.groups = {
            "cloud-01" => ["ubuntu2511_01", "ubuntu2511_02"],
            "all_groups:children" => ["cloud-01"]
        }
    end
end
