---
- name: Install&configure nginx, add users
  hosts: all
  sudo: true
  remote_user: vagrant
  vars:
    users: [ paolo, lucia, arianna, gianluca ]


## NGINX PROVISIONING
  tasks:
  - name: Installing NGINX
    apt: name=nginx update_cache=yes

   ##CUSTOM configurations
#  - name: copy nginx config file
#    copy: src=files/nginx.conf dest=/etc/nginx/sites-available/default

#  - name: enable configuration
#    file: >
#      dest=/etc/nginx/sites-enabled/default
#      src=/etc/nginx/sites-available/default
#      state=link

  - name: copy index.html
    template: src=templates/index.html.j2 dest=/usr/share/nginx/html/index.html
      mode=0644

  - name: Create users
    user: name={{item}} state=present
    with_items: users

  - name: Remove user Paolo
    user: name=paolo state=absent remove=yes

  - name: restart nginx
    service: name=nginx state=restarted
    sudo: yes
## NGINX PROVISIONING

## APACHE PROVISIONING (in contrast to nginx)
#  tasks:
#    - name: install apache2
#      apt: name=apache2 update_cache=yes state=latest
#
#    - name: enabled mod_rewrite
#      apache2_module: name=rewrite state=present
#      notify:
#        - restart apache2
#
#  handlers:
#    - name: restart apache2
#      service: name=apache2 state=restarted
#      sudo: yes
## APACHE PROVISIONING