#Vagrant file with ansible provision
Vagrant.configure(2) do |config|
  config.vm.box="precise32"
  config.vm.box_url = "http://files.vagrantup.com/precise32.box"
  #config.vm.synced_folder "./app", "/var/www/", create:true

  #config.vm.network :public_network, :bridge => "en0: Wi-Fi (AirPort)", ip: "192.168.1.200" # FIXED IP

  # This maps port 8080 on your local machine to port 80 of the Vagrant machine,
  # and port 8443 on your local machine to port 443 on the Vagrant machine.
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "forwarded_port", guest: 443, host: 8443

  config.vm.provision :ansible do |ansible|
    ansible.playbook = "site.yml"
  end
end