---
- name: Install and configure nginx
  hosts: ansibleHost
  sudo: true
  remote_user: vagrant

  tasks:
  - name: NGINX | Updating apt cache
    apt:
      update_cache: yes

  - name: NGINX | Installing NGINX
    apt:
      pkg: nginx
      state: latest
    notify:
      - restart nginx

  handlers:
  - name: restart nginx
    service: name=nginx state=restarted
    sudo: yes
