Vagrant.configure(2) do |config|
  config.vm.box="precise32"
  config.vm.box_url = "http://files.vagrantup.com/precise32.box"
  config.vm.synced_folder ".", "/home/vagrant/src", mount_options: ["dmode=775,fmode=664"], type: "nfs"
  config.vm.network :public_network, :bridge => "en0: Wi-Fi (AirPort)", ip: 192.168.1.200 # FIXED IP
  config.vm.provision "shell", path: "bootstrap.sh"
end