---
- name: Setup Hostname and update servers
  hosts: cloud-01
  sudo: true
  remote_user: vagrant

  tasks:
    # set hostname
    - name: set hostname
      shell: hostnamectl set-hostname "ansible-{{ inventory_hostname }}"

    # Run the equivalent of "apt-get update" as a separate step
    - name: updates a server
      apt: update_cache=yes

    # Run the equivalent of "apt-get upgrade" as a separate step
    #- name: upgrade a server
    #  apt: upgrade=full